// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderViewer.Service.OrderAPI.ContextData;

#nullable disable

namespace OrderViewer.Service.OrderAPI.Migrations
{
    [DbContext(typeof(OrderService_DbContext))]
    [Migration("20250815142222_UpdateProductPrecision")]
    partial class UpdateProductPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderViewer.Service.OrderAPI.Models.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Customer");

                    b.HasIndex("Status");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = new Guid("92ce28bd-2740-4e8a-ae93-723292301c2d"),
                            CreatedAt = new DateTime(2025, 8, 15, 14, 22, 22, 66, DateTimeKind.Utc).AddTicks(118),
                            Customer = "Lewis Hamilton ",
                            Status = 0,
                            Total = 10000.00m
                        });
                });

            modelBuilder.Entity("OrderViewer.Service.OrderAPI.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("OrderId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("e07d5ae8-6a80-4c24-9b8d-a1a63bc3d945"),
                            Name = "Laptop",
                            OrderId = new Guid("92ce28bd-2740-4e8a-ae93-723292301c2d"),
                            Quantity = 1,
                            UnitPrice = 8500m
                        },
                        new
                        {
                            ProductId = new Guid("58ca1033-e6e1-4a92-bb64-97624b66044e"),
                            Name = "Mouse",
                            OrderId = new Guid("92ce28bd-2740-4e8a-ae93-723292301c2d"),
                            Quantity = 2,
                            UnitPrice = 250m
                        },
                        new
                        {
                            ProductId = new Guid("f4d3e8c6-5dfd-49d7-b9fb-dd511557949e"),
                            Name = "Keyboard",
                            OrderId = new Guid("92ce28bd-2740-4e8a-ae93-723292301c2d"),
                            Quantity = 2,
                            UnitPrice = 500m
                        });
                });

            modelBuilder.Entity("OrderViewer.Service.OrderAPI.Models.Product", b =>
                {
                    b.HasOne("OrderViewer.Service.OrderAPI.Models.Order", "Order")
                        .WithMany("Products")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OrderViewer.Service.OrderAPI.Models.Order", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
