// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderViewer.Service.OrderAPI.ContextData;

#nullable disable

namespace OrderViewer.Service.OrderAPI.Migrations
{
    [DbContext(typeof(OrderService_DbContext))]
    [Migration("20250815141705_AddProductsTable")]
    partial class AddProductsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderViewer.Service.OrderAPI.Models.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Customer");

                    b.HasIndex("Status");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = new Guid("006d2937-8811-47dd-b15e-33f2bcf78bf0"),
                            CreatedAt = new DateTime(2025, 8, 15, 14, 17, 5, 41, DateTimeKind.Utc).AddTicks(291),
                            Customer = "Lewis Hamilton ",
                            Status = 0,
                            Total = 10000.00m
                        });
                });

            modelBuilder.Entity("OrderViewer.Service.OrderAPI.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("OrderId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("6aa19957-fcf2-4bb7-8db9-7e77575a4669"),
                            Name = "Laptop",
                            OrderId = new Guid("006d2937-8811-47dd-b15e-33f2bcf78bf0"),
                            Quantity = 1,
                            UnitPrice = 8500m
                        },
                        new
                        {
                            ProductId = new Guid("7c01a8d2-3fca-4969-8b8f-aa7475e03d36"),
                            Name = "Mouse",
                            OrderId = new Guid("006d2937-8811-47dd-b15e-33f2bcf78bf0"),
                            Quantity = 2,
                            UnitPrice = 250m
                        },
                        new
                        {
                            ProductId = new Guid("3c085b93-d7bf-4d74-a386-b9f0e91495a3"),
                            Name = "Keyboard",
                            OrderId = new Guid("006d2937-8811-47dd-b15e-33f2bcf78bf0"),
                            Quantity = 2,
                            UnitPrice = 500m
                        });
                });

            modelBuilder.Entity("OrderViewer.Service.OrderAPI.Models.Product", b =>
                {
                    b.HasOne("OrderViewer.Service.OrderAPI.Models.Order", "Order")
                        .WithMany("Products")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OrderViewer.Service.OrderAPI.Models.Order", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
