// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderViewer.Service.OrderAPI.ContextData;

#nullable disable

namespace OrderViewer.Service.OrderAPI.Migrations
{
    [DbContext(typeof(OrderService_DbContext))]
    [Migration("20250815162556_OrderProductData")]
    partial class OrderProductData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderViewer.Service.OrderAPI.Models.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Customer");

                    b.HasIndex("Status");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = new Guid("859b6a9e-0d59-41e6-8007-c1977fc47e36"),
                            CreatedAt = new DateTime(2025, 7, 21, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7052),
                            Customer = "Valtteri Bottas",
                            Status = 2,
                            Total = 17107.19m
                        },
                        new
                        {
                            OrderId = new Guid("95f9b3a7-b3ee-44f7-9a85-8d45d8f3f10d"),
                            CreatedAt = new DateTime(2025, 7, 24, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7111),
                            Customer = "Lando Norris",
                            Status = 1,
                            Total = 26032.74m
                        },
                        new
                        {
                            OrderId = new Guid("cd0275d6-3d73-4164-9928-bc6e48ca36c0"),
                            CreatedAt = new DateTime(2025, 6, 26, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7122),
                            Customer = "Max Verstappen",
                            Status = 3,
                            Total = 14790.15m
                        },
                        new
                        {
                            OrderId = new Guid("9f7c830b-07ec-48b9-a5c1-fd2736bfcae2"),
                            CreatedAt = new DateTime(2025, 7, 10, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7132),
                            Customer = "Fernando Alonso",
                            Status = 1,
                            Total = 15462.52m
                        },
                        new
                        {
                            OrderId = new Guid("aa972f5b-a466-484b-978b-7dcd740d9d57"),
                            CreatedAt = new DateTime(2025, 7, 3, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7138),
                            Customer = "Lewis Hamilton",
                            Status = 3,
                            Total = 37264.86m
                        },
                        new
                        {
                            OrderId = new Guid("bdeb1778-ef64-4b65-b37b-704a0485f338"),
                            CreatedAt = new DateTime(2025, 5, 20, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7149),
                            Customer = "Fernando Alonso",
                            Status = 1,
                            Total = 25587.14m
                        },
                        new
                        {
                            OrderId = new Guid("a953969f-01bf-487f-898a-76a4ccb9df34"),
                            CreatedAt = new DateTime(2025, 7, 24, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7159),
                            Customer = "Lewis Hamilton",
                            Status = 0,
                            Total = 4964.80m
                        },
                        new
                        {
                            OrderId = new Guid("4e17370c-655c-4024-a0fb-5ad5d41af532"),
                            CreatedAt = new DateTime(2025, 5, 26, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7164),
                            Customer = "Valtteri Bottas",
                            Status = 0,
                            Total = 14735.32m
                        },
                        new
                        {
                            OrderId = new Guid("722f677b-8dc1-4b8d-b527-d89388737d0a"),
                            CreatedAt = new DateTime(2025, 8, 5, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7171),
                            Customer = "Banale",
                            Status = 0,
                            Total = 1489.77m
                        },
                        new
                        {
                            OrderId = new Guid("1cb82f7a-9a39-4ac5-962d-fb3be8b7f31e"),
                            CreatedAt = new DateTime(2025, 8, 4, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7176),
                            Customer = "Fernando Alonso",
                            Status = 2,
                            Total = 13751.99m
                        },
                        new
                        {
                            OrderId = new Guid("e58fb697-c720-46ec-8405-ce077deb40af"),
                            CreatedAt = new DateTime(2025, 6, 17, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7218),
                            Customer = "Banale",
                            Status = 0,
                            Total = 18578.02m
                        },
                        new
                        {
                            OrderId = new Guid("41038d29-3764-4b34-aeb0-e3c87f950f24"),
                            CreatedAt = new DateTime(2025, 8, 14, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7224),
                            Customer = "Lando Norris",
                            Status = 2,
                            Total = 23394.03m
                        },
                        new
                        {
                            OrderId = new Guid("23447a11-9916-42dd-93e5-09fe025224e9"),
                            CreatedAt = new DateTime(2025, 7, 22, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7235),
                            Customer = "Valtteri Bottas",
                            Status = 2,
                            Total = 12677.96m
                        },
                        new
                        {
                            OrderId = new Guid("d8de140a-847e-4d42-a658-6754133b7f8d"),
                            CreatedAt = new DateTime(2025, 7, 29, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7240),
                            Customer = "Lando Norris",
                            Status = 0,
                            Total = 20437.76m
                        },
                        new
                        {
                            OrderId = new Guid("b57898a6-9445-450c-9bea-8ea7f33e6b97"),
                            CreatedAt = new DateTime(2025, 5, 27, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7248),
                            Customer = "Max Verstappen",
                            Status = 3,
                            Total = 29899.88m
                        },
                        new
                        {
                            OrderId = new Guid("4c790b96-3e71-442c-8412-b08ac983771b"),
                            CreatedAt = new DateTime(2025, 8, 12, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7258),
                            Customer = "Sebastian Vettel",
                            Status = 3,
                            Total = 24447.44m
                        },
                        new
                        {
                            OrderId = new Guid("bf4fa2bc-10e5-41ee-abdf-e49c261e3179"),
                            CreatedAt = new DateTime(2025, 6, 2, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7267),
                            Customer = "Sebastian Vettel",
                            Status = 0,
                            Total = 395.70m
                        },
                        new
                        {
                            OrderId = new Guid("f1f5d7ec-381f-4341-bb6d-9f7001349123"),
                            CreatedAt = new DateTime(2025, 6, 5, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7274),
                            Customer = "Fernando Alonso",
                            Status = 0,
                            Total = 28484.16m
                        },
                        new
                        {
                            OrderId = new Guid("2a8aa5cc-e370-479f-88cf-199498c81410"),
                            CreatedAt = new DateTime(2025, 6, 18, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7281),
                            Customer = "Daniel Ricciardo",
                            Status = 3,
                            Total = 7262.68m
                        },
                        new
                        {
                            OrderId = new Guid("4703c966-e97a-4ffe-97bb-922a9a9f0c2b"),
                            CreatedAt = new DateTime(2025, 8, 9, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7288),
                            Customer = "Fernando Alonso",
                            Status = 3,
                            Total = 20040.70m
                        },
                        new
                        {
                            OrderId = new Guid("7c08ec62-77f2-4573-893a-898007c19b0b"),
                            CreatedAt = new DateTime(2025, 8, 8, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7295),
                            Customer = "Daniel Ricciardo",
                            Status = 2,
                            Total = 11859.49m
                        },
                        new
                        {
                            OrderId = new Guid("40d266c7-38d2-40e9-9894-7ee7343ff16e"),
                            CreatedAt = new DateTime(2025, 5, 22, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7308),
                            Customer = "Sebastian Vettel",
                            Status = 3,
                            Total = 12857.49m
                        },
                        new
                        {
                            OrderId = new Guid("2fe7525d-e8d5-42ec-8728-2d4cc86c7071"),
                            CreatedAt = new DateTime(2025, 5, 23, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7313),
                            Customer = "Valtteri Bottas",
                            Status = 0,
                            Total = 1518.04m
                        },
                        new
                        {
                            OrderId = new Guid("c72b0369-3ca7-4a37-8650-206b0aed7614"),
                            CreatedAt = new DateTime(2025, 7, 11, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7317),
                            Customer = "Max Verstappen",
                            Status = 2,
                            Total = 11141.20m
                        },
                        new
                        {
                            OrderId = new Guid("6d618cf9-1e32-47aa-9cad-b99990d0580d"),
                            CreatedAt = new DateTime(2025, 8, 4, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7328),
                            Customer = "Sebastian Vettel",
                            Status = 0,
                            Total = 12918.53m
                        },
                        new
                        {
                            OrderId = new Guid("df0d2884-4250-4df6-bb3b-be0362560d7e"),
                            CreatedAt = new DateTime(2025, 6, 1, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7336),
                            Customer = "Sebastian Vettel",
                            Status = 0,
                            Total = 9521.96m
                        },
                        new
                        {
                            OrderId = new Guid("5ca258b5-6612-4f1d-84c6-05dea1c9dd44"),
                            CreatedAt = new DateTime(2025, 7, 1, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7347),
                            Customer = "Banale",
                            Status = 2,
                            Total = 13790.01m
                        },
                        new
                        {
                            OrderId = new Guid("e99ee60e-9c59-4156-95dd-cfb63a9508bf"),
                            CreatedAt = new DateTime(2025, 6, 16, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7354),
                            Customer = "Lando Norris",
                            Status = 3,
                            Total = 1575.94m
                        },
                        new
                        {
                            OrderId = new Guid("1adf054d-b6eb-40da-915b-38cba82c5b2c"),
                            CreatedAt = new DateTime(2025, 5, 18, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7358),
                            Customer = "Sebastian Vettel",
                            Status = 3,
                            Total = 14396.59m
                        },
                        new
                        {
                            OrderId = new Guid("704ac39c-4331-491d-a8ec-01375655eeb5"),
                            CreatedAt = new DateTime(2025, 7, 25, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7364),
                            Customer = "Lewis Hamilton",
                            Status = 2,
                            Total = 31244.21m
                        },
                        new
                        {
                            OrderId = new Guid("65589077-31fa-41e3-a271-2c9af2052046"),
                            CreatedAt = new DateTime(2025, 7, 16, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7430),
                            Customer = "Lando Norris",
                            Status = 1,
                            Total = 43638.81m
                        },
                        new
                        {
                            OrderId = new Guid("364c23bf-7770-4b90-87cc-4dbe51a72f80"),
                            CreatedAt = new DateTime(2025, 7, 26, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7443),
                            Customer = "Banale",
                            Status = 2,
                            Total = 8742.62m
                        },
                        new
                        {
                            OrderId = new Guid("cb51b1e5-1146-4351-837f-d5a2100ab289"),
                            CreatedAt = new DateTime(2025, 7, 17, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7450),
                            Customer = "Banale",
                            Status = 0,
                            Total = 9551.34m
                        },
                        new
                        {
                            OrderId = new Guid("90085c45-7a4e-49a6-8b9a-9ec70297b4ad"),
                            CreatedAt = new DateTime(2025, 5, 24, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7455),
                            Customer = "Daniel Ricciardo",
                            Status = 0,
                            Total = 47071.94m
                        },
                        new
                        {
                            OrderId = new Guid("8ee3859f-a583-4fd8-8a20-46b5d84a47a0"),
                            CreatedAt = new DateTime(2025, 6, 30, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7468),
                            Customer = "Shaka",
                            Status = 1,
                            Total = 4219.88m
                        },
                        new
                        {
                            OrderId = new Guid("8c1b2538-9008-499f-9f16-95b69960eced"),
                            CreatedAt = new DateTime(2025, 7, 14, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7472),
                            Customer = "Valtteri Bottas",
                            Status = 0,
                            Total = 29375.29m
                        },
                        new
                        {
                            OrderId = new Guid("5da8ed8e-b31c-453a-a215-479048514319"),
                            CreatedAt = new DateTime(2025, 6, 13, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7483),
                            Customer = "Shaka",
                            Status = 1,
                            Total = 21755.86m
                        },
                        new
                        {
                            OrderId = new Guid("7f17be03-7c57-4a02-b6ff-5d51a997d25c"),
                            CreatedAt = new DateTime(2025, 5, 19, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7489),
                            Customer = "Daniel Ricciardo",
                            Status = 3,
                            Total = 26245.30m
                        },
                        new
                        {
                            OrderId = new Guid("02b34547-c1a4-42b4-ab37-1a799d3a5417"),
                            CreatedAt = new DateTime(2025, 6, 4, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7499),
                            Customer = "Daniel Ricciardo",
                            Status = 1,
                            Total = 20940.11m
                        },
                        new
                        {
                            OrderId = new Guid("3c90739f-80f9-4fee-aa41-7fcf1bc27551"),
                            CreatedAt = new DateTime(2025, 8, 10, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7507),
                            Customer = "Sebastian Vettel",
                            Status = 3,
                            Total = 5623.90m
                        },
                        new
                        {
                            OrderId = new Guid("cd3dfae4-336e-43a1-af13-d215fc01c27c"),
                            CreatedAt = new DateTime(2025, 8, 15, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7513),
                            Customer = "Lewis Hamilton",
                            Status = 0,
                            Total = 14635.01m
                        },
                        new
                        {
                            OrderId = new Guid("01916843-8a88-4c4f-8d52-2c3758672a6d"),
                            CreatedAt = new DateTime(2025, 5, 21, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7522),
                            Customer = "Fernando Alonso",
                            Status = 3,
                            Total = 9031.19m
                        },
                        new
                        {
                            OrderId = new Guid("5d6401b6-1d27-4f30-96d8-aee89ece5604"),
                            CreatedAt = new DateTime(2025, 7, 29, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7527),
                            Customer = "Charles Leclerc",
                            Status = 1,
                            Total = 6046.95m
                        },
                        new
                        {
                            OrderId = new Guid("7e4c0803-df8b-4a7d-a58a-f8a104595acb"),
                            CreatedAt = new DateTime(2025, 7, 25, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7533),
                            Customer = "Sebastian Vettel",
                            Status = 2,
                            Total = 8691.16m
                        },
                        new
                        {
                            OrderId = new Guid("88d81a15-bc6c-495e-8f3f-218a5b85fac2"),
                            CreatedAt = new DateTime(2025, 6, 24, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7538),
                            Customer = "Daniel Ricciardo",
                            Status = 0,
                            Total = 48465.24m
                        },
                        new
                        {
                            OrderId = new Guid("e115edaa-ea9f-4bff-babd-671ceeafe26c"),
                            CreatedAt = new DateTime(2025, 6, 3, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7548),
                            Customer = "Sebastian Vettel",
                            Status = 0,
                            Total = 20846.84m
                        },
                        new
                        {
                            OrderId = new Guid("671212b2-8732-441e-81c9-7bfa1bbca4e6"),
                            CreatedAt = new DateTime(2025, 7, 6, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7554),
                            Customer = "Shaka",
                            Status = 0,
                            Total = 36019.27m
                        },
                        new
                        {
                            OrderId = new Guid("8d04a8e4-5c06-4d30-b011-b7fe9af5bc21"),
                            CreatedAt = new DateTime(2025, 7, 12, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7565),
                            Customer = "Banale",
                            Status = 2,
                            Total = 37677.62m
                        },
                        new
                        {
                            OrderId = new Guid("595f3d82-1954-4398-83f5-38bb445abe6c"),
                            CreatedAt = new DateTime(2025, 7, 26, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7574),
                            Customer = "Lewis Hamilton",
                            Status = 0,
                            Total = 23160.79m
                        },
                        new
                        {
                            OrderId = new Guid("2cbde594-d503-4b9e-a200-2bdf5c2416f6"),
                            CreatedAt = new DateTime(2025, 7, 23, 16, 25, 56, 278, DateTimeKind.Utc).AddTicks(7630),
                            Customer = "Lewis Hamilton",
                            Status = 2,
                            Total = 36300.46m
                        });
                });

            modelBuilder.Entity("OrderViewer.Service.OrderAPI.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("OrderId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("218e9a16-15bf-4ee0-8ccd-e9fc8bec2ad5"),
                            Name = "Mouse",
                            OrderId = new Guid("859b6a9e-0d59-41e6-8007-c1977fc47e36"),
                            Quantity = 2,
                            UnitPrice = 1266.81m
                        },
                        new
                        {
                            ProductId = new Guid("ffcb4be9-3cda-432b-b90d-63bc7e0be747"),
                            Name = "Mouse",
                            OrderId = new Guid("859b6a9e-0d59-41e6-8007-c1977fc47e36"),
                            Quantity = 2,
                            UnitPrice = 3567.71m
                        },
                        new
                        {
                            ProductId = new Guid("f8081dff-3773-4aca-824d-2e33986964a9"),
                            Name = "Monitor",
                            OrderId = new Guid("859b6a9e-0d59-41e6-8007-c1977fc47e36"),
                            Quantity = 1,
                            UnitPrice = 4236.43m
                        },
                        new
                        {
                            ProductId = new Guid("6d0ece61-ff69-4b35-8a54-3fd5c10c53f2"),
                            Name = "Webcam",
                            OrderId = new Guid("859b6a9e-0d59-41e6-8007-c1977fc47e36"),
                            Quantity = 1,
                            UnitPrice = 3201.72m
                        },
                        new
                        {
                            ProductId = new Guid("66ccde33-5f58-4d41-80af-9d538241f108"),
                            Name = "Printer",
                            OrderId = new Guid("95f9b3a7-b3ee-44f7-9a85-8d45d8f3f10d"),
                            Quantity = 4,
                            UnitPrice = 2520.35m
                        },
                        new
                        {
                            ProductId = new Guid("048fd49d-e684-43e4-b0fe-87a497ad6a96"),
                            Name = "USB Drive",
                            OrderId = new Guid("95f9b3a7-b3ee-44f7-9a85-8d45d8f3f10d"),
                            Quantity = 2,
                            UnitPrice = 2061.60m
                        },
                        new
                        {
                            ProductId = new Guid("35bf07a8-2127-45a6-acbf-25ed7b1e7dca"),
                            Name = "Headset",
                            OrderId = new Guid("95f9b3a7-b3ee-44f7-9a85-8d45d8f3f10d"),
                            Quantity = 3,
                            UnitPrice = 2694.96m
                        },
                        new
                        {
                            ProductId = new Guid("22aa67c2-222e-427a-9414-7510d785536c"),
                            Name = "Mouse",
                            OrderId = new Guid("95f9b3a7-b3ee-44f7-9a85-8d45d8f3f10d"),
                            Quantity = 1,
                            UnitPrice = 3743.26m
                        },
                        new
                        {
                            ProductId = new Guid("47a67ae1-3518-4005-a2be-15ce15ec04bd"),
                            Name = "Headset",
                            OrderId = new Guid("cd0275d6-3d73-4164-9928-bc6e48ca36c0"),
                            Quantity = 3,
                            UnitPrice = 4607.85m
                        },
                        new
                        {
                            ProductId = new Guid("532f70b7-7a25-47be-b25d-14a614920098"),
                            Name = "Headset",
                            OrderId = new Guid("cd0275d6-3d73-4164-9928-bc6e48ca36c0"),
                            Quantity = 2,
                            UnitPrice = 483.30m
                        },
                        new
                        {
                            ProductId = new Guid("1c0c8348-c1a7-4847-9c7f-9e076699652d"),
                            Name = "Laptop",
                            OrderId = new Guid("9f7c830b-07ec-48b9-a5c1-fd2736bfcae2"),
                            Quantity = 4,
                            UnitPrice = 3376.84m
                        },
                        new
                        {
                            ProductId = new Guid("65bc4b92-6fca-480b-b124-910fd627e28a"),
                            Name = "Printer",
                            OrderId = new Guid("9f7c830b-07ec-48b9-a5c1-fd2736bfcae2"),
                            Quantity = 1,
                            UnitPrice = 1955.16m
                        },
                        new
                        {
                            ProductId = new Guid("5b9a61d2-2a59-48c7-b040-55964dc1f96e"),
                            Name = "USB Drive",
                            OrderId = new Guid("aa972f5b-a466-484b-978b-7dcd740d9d57"),
                            Quantity = 3,
                            UnitPrice = 4051.11m
                        },
                        new
                        {
                            ProductId = new Guid("d2f5141d-14d2-43c9-8978-57affdce2e4e"),
                            Name = "Laptop",
                            OrderId = new Guid("aa972f5b-a466-484b-978b-7dcd740d9d57"),
                            Quantity = 3,
                            UnitPrice = 2619.36m
                        },
                        new
                        {
                            ProductId = new Guid("0f303d56-f4e0-4803-a53f-7c604f5b94cf"),
                            Name = "Webcam",
                            OrderId = new Guid("aa972f5b-a466-484b-978b-7dcd740d9d57"),
                            Quantity = 4,
                            UnitPrice = 3851.60m
                        },
                        new
                        {
                            ProductId = new Guid("b2172cad-03ff-4ab8-aa56-f73492220ca1"),
                            Name = "Mouse",
                            OrderId = new Guid("aa972f5b-a466-484b-978b-7dcd740d9d57"),
                            Quantity = 1,
                            UnitPrice = 1847.05m
                        },
                        new
                        {
                            ProductId = new Guid("5254739c-4563-40f6-b731-006bbc0b7082"),
                            Name = "Smartphone",
                            OrderId = new Guid("bdeb1778-ef64-4b65-b37b-704a0485f338"),
                            Quantity = 4,
                            UnitPrice = 1574.86m
                        },
                        new
                        {
                            ProductId = new Guid("d251ba80-51a2-460c-a045-2f4dcf0f4ee7"),
                            Name = "Laptop",
                            OrderId = new Guid("bdeb1778-ef64-4b65-b37b-704a0485f338"),
                            Quantity = 4,
                            UnitPrice = 2921.28m
                        },
                        new
                        {
                            ProductId = new Guid("1c174b13-3b65-4e8a-bfa0-2fa397410666"),
                            Name = "Keyboard",
                            OrderId = new Guid("bdeb1778-ef64-4b65-b37b-704a0485f338"),
                            Quantity = 2,
                            UnitPrice = 3801.29m
                        },
                        new
                        {
                            ProductId = new Guid("5759d2d7-5974-4f92-a1c3-2a0a63485643"),
                            Name = "Headset",
                            OrderId = new Guid("a953969f-01bf-487f-898a-76a4ccb9df34"),
                            Quantity = 4,
                            UnitPrice = 1241.20m
                        },
                        new
                        {
                            ProductId = new Guid("abf97b42-dbac-4ed2-a4d8-c6161252bfb9"),
                            Name = "Smartphone",
                            OrderId = new Guid("4e17370c-655c-4024-a0fb-5ad5d41af532"),
                            Quantity = 3,
                            UnitPrice = 1178.04m
                        },
                        new
                        {
                            ProductId = new Guid("96c78fa6-894d-4b3f-b428-a16212be350d"),
                            Name = "Headset",
                            OrderId = new Guid("4e17370c-655c-4024-a0fb-5ad5d41af532"),
                            Quantity = 4,
                            UnitPrice = 2800.30m
                        },
                        new
                        {
                            ProductId = new Guid("96546b7e-9bf7-4635-9e79-7b7c81f0df47"),
                            Name = "Keyboard",
                            OrderId = new Guid("722f677b-8dc1-4b8d-b527-d89388737d0a"),
                            Quantity = 3,
                            UnitPrice = 496.59m
                        },
                        new
                        {
                            ProductId = new Guid("737cb01f-f411-467e-887d-7bfe383104f0"),
                            Name = "Laptop",
                            OrderId = new Guid("1cb82f7a-9a39-4ac5-962d-fb3be8b7f31e"),
                            Quantity = 4,
                            UnitPrice = 457.94m
                        },
                        new
                        {
                            ProductId = new Guid("5b55e6fd-9d67-430a-ae9b-d12bff6ca8da"),
                            Name = "USB Drive",
                            OrderId = new Guid("1cb82f7a-9a39-4ac5-962d-fb3be8b7f31e"),
                            Quantity = 2,
                            UnitPrice = 3974.17m
                        },
                        new
                        {
                            ProductId = new Guid("3e1b0f6e-a89b-4214-bf61-ccc2fe7eb8b3"),
                            Name = "Headset",
                            OrderId = new Guid("1cb82f7a-9a39-4ac5-962d-fb3be8b7f31e"),
                            Quantity = 1,
                            UnitPrice = 3971.89m
                        },
                        new
                        {
                            ProductId = new Guid("59318be8-41bd-44b0-a0ad-7c90316d3010"),
                            Name = "Printer",
                            OrderId = new Guid("e58fb697-c720-46ec-8405-ce077deb40af"),
                            Quantity = 4,
                            UnitPrice = 2821.12m
                        },
                        new
                        {
                            ProductId = new Guid("36e3f6ea-3b42-4f4c-a68d-4282f8d775b9"),
                            Name = "Smartphone",
                            OrderId = new Guid("e58fb697-c720-46ec-8405-ce077deb40af"),
                            Quantity = 2,
                            UnitPrice = 3646.77m
                        },
                        new
                        {
                            ProductId = new Guid("ab30e394-7b7c-4ed2-9acc-d48a6bfc499f"),
                            Name = "Monitor",
                            OrderId = new Guid("41038d29-3764-4b34-aeb0-e3c87f950f24"),
                            Quantity = 2,
                            UnitPrice = 1661.16m
                        },
                        new
                        {
                            ProductId = new Guid("e993a310-bf0c-42ba-a6b4-cf406d6a38b4"),
                            Name = "Laptop",
                            OrderId = new Guid("41038d29-3764-4b34-aeb0-e3c87f950f24"),
                            Quantity = 3,
                            UnitPrice = 4927.38m
                        },
                        new
                        {
                            ProductId = new Guid("88d52047-5278-4786-beb8-1f02dcd8d03b"),
                            Name = "Printer",
                            OrderId = new Guid("41038d29-3764-4b34-aeb0-e3c87f950f24"),
                            Quantity = 3,
                            UnitPrice = 1468.70m
                        },
                        new
                        {
                            ProductId = new Guid("51537ee2-6991-40c0-ae2a-4e874b3f8bc3"),
                            Name = "Tablet",
                            OrderId = new Guid("41038d29-3764-4b34-aeb0-e3c87f950f24"),
                            Quantity = 1,
                            UnitPrice = 883.47m
                        },
                        new
                        {
                            ProductId = new Guid("1c2e2940-6e9b-4f1a-8002-f43d4a0bee0b"),
                            Name = "Smartphone",
                            OrderId = new Guid("23447a11-9916-42dd-93e5-09fe025224e9"),
                            Quantity = 4,
                            UnitPrice = 3169.49m
                        },
                        new
                        {
                            ProductId = new Guid("cc2f3830-e258-413f-a259-2386152ba032"),
                            Name = "Laptop",
                            OrderId = new Guid("d8de140a-847e-4d42-a658-6754133b7f8d"),
                            Quantity = 4,
                            UnitPrice = 3162.46m
                        },
                        new
                        {
                            ProductId = new Guid("359b5b0f-c428-4f6c-a5e3-d39b889f8cb7"),
                            Name = "Printer",
                            OrderId = new Guid("d8de140a-847e-4d42-a658-6754133b7f8d"),
                            Quantity = 4,
                            UnitPrice = 1946.98m
                        },
                        new
                        {
                            ProductId = new Guid("19372f44-e4c3-4520-9404-8894d26ac1f2"),
                            Name = "Monitor",
                            OrderId = new Guid("b57898a6-9445-450c-9bea-8ea7f33e6b97"),
                            Quantity = 2,
                            UnitPrice = 2577.88m
                        },
                        new
                        {
                            ProductId = new Guid("713cb899-37d4-4a40-bae5-36ab58d1aa8a"),
                            Name = "Laptop",
                            OrderId = new Guid("b57898a6-9445-450c-9bea-8ea7f33e6b97"),
                            Quantity = 4,
                            UnitPrice = 3179.46m
                        },
                        new
                        {
                            ProductId = new Guid("8909e007-91fd-476f-89ed-b34d3a3b0d48"),
                            Name = "Laptop",
                            OrderId = new Guid("b57898a6-9445-450c-9bea-8ea7f33e6b97"),
                            Quantity = 4,
                            UnitPrice = 585.63m
                        },
                        new
                        {
                            ProductId = new Guid("579439ca-7f74-449a-8bdb-fe005c8166a0"),
                            Name = "Keyboard",
                            OrderId = new Guid("b57898a6-9445-450c-9bea-8ea7f33e6b97"),
                            Quantity = 4,
                            UnitPrice = 2420.94m
                        },
                        new
                        {
                            ProductId = new Guid("59b611e4-1867-4c8a-99bb-72dab95a947b"),
                            Name = "Smartphone",
                            OrderId = new Guid("4c790b96-3e71-442c-8412-b08ac983771b"),
                            Quantity = 4,
                            UnitPrice = 1480.97m
                        },
                        new
                        {
                            ProductId = new Guid("7248e3f8-4a32-47a9-8187-8ad54fc9426f"),
                            Name = "Monitor",
                            OrderId = new Guid("4c790b96-3e71-442c-8412-b08ac983771b"),
                            Quantity = 3,
                            UnitPrice = 4005.61m
                        },
                        new
                        {
                            ProductId = new Guid("3a7f437c-d7d1-4c2b-ae88-e336f7a7c388"),
                            Name = "Monitor",
                            OrderId = new Guid("4c790b96-3e71-442c-8412-b08ac983771b"),
                            Quantity = 2,
                            UnitPrice = 2263.59m
                        },
                        new
                        {
                            ProductId = new Guid("be957f79-366c-4e33-916c-9b588dda7bb3"),
                            Name = "Printer",
                            OrderId = new Guid("4c790b96-3e71-442c-8412-b08ac983771b"),
                            Quantity = 3,
                            UnitPrice = 659.85m
                        },
                        new
                        {
                            ProductId = new Guid("ea67b0ae-3015-4914-994e-49bd2558ca4b"),
                            Name = "Printer",
                            OrderId = new Guid("bf4fa2bc-10e5-41ee-abdf-e49c261e3179"),
                            Quantity = 2,
                            UnitPrice = 197.85m
                        },
                        new
                        {
                            ProductId = new Guid("bd64a0bd-86cd-433b-a5d1-a1d886eed030"),
                            Name = "Tablet",
                            OrderId = new Guid("f1f5d7ec-381f-4341-bb6d-9f7001349123"),
                            Quantity = 2,
                            UnitPrice = 309.40m
                        },
                        new
                        {
                            ProductId = new Guid("0150adea-f338-46af-9844-565656fad216"),
                            Name = "Tablet",
                            OrderId = new Guid("f1f5d7ec-381f-4341-bb6d-9f7001349123"),
                            Quantity = 4,
                            UnitPrice = 3677.32m
                        },
                        new
                        {
                            ProductId = new Guid("59af9d9e-db8f-4e42-b567-760d4818b3b5"),
                            Name = "Keyboard",
                            OrderId = new Guid("f1f5d7ec-381f-4341-bb6d-9f7001349123"),
                            Quantity = 3,
                            UnitPrice = 4385.36m
                        },
                        new
                        {
                            ProductId = new Guid("00e3ca5b-fe6a-42dd-a0be-7b94c4befbd4"),
                            Name = "Monitor",
                            OrderId = new Guid("2a8aa5cc-e370-479f-88cf-199498c81410"),
                            Quantity = 2,
                            UnitPrice = 3631.34m
                        },
                        new
                        {
                            ProductId = new Guid("133bbb3c-1ee3-4aaf-ab56-25a28e29a558"),
                            Name = "Mouse",
                            OrderId = new Guid("4703c966-e97a-4ffe-97bb-922a9a9f0c2b"),
                            Quantity = 2,
                            UnitPrice = 2905.00m
                        },
                        new
                        {
                            ProductId = new Guid("a2901ccf-f030-44e1-8c76-aefe106037d2"),
                            Name = "USB Drive",
                            OrderId = new Guid("4703c966-e97a-4ffe-97bb-922a9a9f0c2b"),
                            Quantity = 4,
                            UnitPrice = 1495.73m
                        },
                        new
                        {
                            ProductId = new Guid("1bc24cc1-8196-4e9d-9edf-3a43ad7aecf2"),
                            Name = "Keyboard",
                            OrderId = new Guid("4703c966-e97a-4ffe-97bb-922a9a9f0c2b"),
                            Quantity = 2,
                            UnitPrice = 4123.89m
                        },
                        new
                        {
                            ProductId = new Guid("6d882db3-8941-47d1-9bc7-d9419e8b6d7c"),
                            Name = "Laptop",
                            OrderId = new Guid("7c08ec62-77f2-4573-893a-898007c19b0b"),
                            Quantity = 4,
                            UnitPrice = 496.00m
                        },
                        new
                        {
                            ProductId = new Guid("65d07be2-99a8-4d2e-a4ae-55612140cc4d"),
                            Name = "Headset",
                            OrderId = new Guid("7c08ec62-77f2-4573-893a-898007c19b0b"),
                            Quantity = 1,
                            UnitPrice = 1567.43m
                        },
                        new
                        {
                            ProductId = new Guid("b5318312-72bd-4bfe-8da6-36be65b706b2"),
                            Name = "Laptop",
                            OrderId = new Guid("7c08ec62-77f2-4573-893a-898007c19b0b"),
                            Quantity = 1,
                            UnitPrice = 3572.80m
                        },
                        new
                        {
                            ProductId = new Guid("8786f3c4-2373-47ae-8997-505a19f748e6"),
                            Name = "Monitor",
                            OrderId = new Guid("7c08ec62-77f2-4573-893a-898007c19b0b"),
                            Quantity = 2,
                            UnitPrice = 1491.75m
                        },
                        new
                        {
                            ProductId = new Guid("1fd28e2e-9ef7-4a82-a745-27ba6765fd89"),
                            Name = "Monitor",
                            OrderId = new Guid("7c08ec62-77f2-4573-893a-898007c19b0b"),
                            Quantity = 1,
                            UnitPrice = 1751.76m
                        },
                        new
                        {
                            ProductId = new Guid("347230b1-3145-44dd-9d60-cef27f0626b3"),
                            Name = "Keyboard",
                            OrderId = new Guid("40d266c7-38d2-40e9-9894-7ee7343ff16e"),
                            Quantity = 3,
                            UnitPrice = 4285.83m
                        },
                        new
                        {
                            ProductId = new Guid("9595927d-a7c3-421b-b61f-7206784b77d2"),
                            Name = "Tablet",
                            OrderId = new Guid("2fe7525d-e8d5-42ec-8728-2d4cc86c7071"),
                            Quantity = 1,
                            UnitPrice = 1518.04m
                        },
                        new
                        {
                            ProductId = new Guid("1d96522e-6108-4354-b071-fbd1447a1571"),
                            Name = "Laptop",
                            OrderId = new Guid("c72b0369-3ca7-4a37-8650-206b0aed7614"),
                            Quantity = 1,
                            UnitPrice = 738.57m
                        },
                        new
                        {
                            ProductId = new Guid("2472af87-b377-4738-9fe4-862538cb7ba3"),
                            Name = "Keyboard",
                            OrderId = new Guid("c72b0369-3ca7-4a37-8650-206b0aed7614"),
                            Quantity = 1,
                            UnitPrice = 4064.67m
                        },
                        new
                        {
                            ProductId = new Guid("af9eca7e-e89e-4867-8190-85cb3c43ad48"),
                            Name = "USB Drive",
                            OrderId = new Guid("c72b0369-3ca7-4a37-8650-206b0aed7614"),
                            Quantity = 3,
                            UnitPrice = 898.64m
                        },
                        new
                        {
                            ProductId = new Guid("dd77df27-21fd-4843-8bbd-3838cf1b82ee"),
                            Name = "Laptop",
                            OrderId = new Guid("c72b0369-3ca7-4a37-8650-206b0aed7614"),
                            Quantity = 2,
                            UnitPrice = 1821.02m
                        },
                        new
                        {
                            ProductId = new Guid("3bb40ad1-7ba4-4d0a-9a1d-bf26bb92946a"),
                            Name = "USB Drive",
                            OrderId = new Guid("6d618cf9-1e32-47aa-9cad-b99990d0580d"),
                            Quantity = 1,
                            UnitPrice = 392.26m
                        },
                        new
                        {
                            ProductId = new Guid("197448d3-f8d3-4bdd-bfe4-486b51ed59f9"),
                            Name = "Smartphone",
                            OrderId = new Guid("6d618cf9-1e32-47aa-9cad-b99990d0580d"),
                            Quantity = 1,
                            UnitPrice = 4281.71m
                        },
                        new
                        {
                            ProductId = new Guid("fcdfa4dc-31e7-47f1-8633-bae9a956c69d"),
                            Name = "Headset",
                            OrderId = new Guid("6d618cf9-1e32-47aa-9cad-b99990d0580d"),
                            Quantity = 2,
                            UnitPrice = 4122.28m
                        },
                        new
                        {
                            ProductId = new Guid("c33f16b5-fe1e-4e81-b613-5301e3df092e"),
                            Name = "USB Drive",
                            OrderId = new Guid("df0d2884-4250-4df6-bb3b-be0362560d7e"),
                            Quantity = 1,
                            UnitPrice = 388.91m
                        },
                        new
                        {
                            ProductId = new Guid("4a7e65a6-4981-4a13-be60-4f6e65b5fdb3"),
                            Name = "Monitor",
                            OrderId = new Guid("df0d2884-4250-4df6-bb3b-be0362560d7e"),
                            Quantity = 2,
                            UnitPrice = 2275.86m
                        },
                        new
                        {
                            ProductId = new Guid("b74ec874-74de-4d30-94ad-5e26bd5dfb6f"),
                            Name = "Tablet",
                            OrderId = new Guid("df0d2884-4250-4df6-bb3b-be0362560d7e"),
                            Quantity = 1,
                            UnitPrice = 2867.61m
                        },
                        new
                        {
                            ProductId = new Guid("5711761c-e1e8-426e-87c4-d63ec9cd1f1a"),
                            Name = "Webcam",
                            OrderId = new Guid("df0d2884-4250-4df6-bb3b-be0362560d7e"),
                            Quantity = 1,
                            UnitPrice = 1713.72m
                        },
                        new
                        {
                            ProductId = new Guid("96016659-cd3e-446e-858c-f92941ef957a"),
                            Name = "Mouse",
                            OrderId = new Guid("5ca258b5-6612-4f1d-84c6-05dea1c9dd44"),
                            Quantity = 3,
                            UnitPrice = 614.58m
                        },
                        new
                        {
                            ProductId = new Guid("26936997-cc09-4c26-b01d-4aa331ec244a"),
                            Name = "Mouse",
                            OrderId = new Guid("5ca258b5-6612-4f1d-84c6-05dea1c9dd44"),
                            Quantity = 3,
                            UnitPrice = 3982.09m
                        },
                        new
                        {
                            ProductId = new Guid("84bfe5fb-7885-41f8-83c3-e6fcd3e54b6b"),
                            Name = "Monitor",
                            OrderId = new Guid("e99ee60e-9c59-4156-95dd-cfb63a9508bf"),
                            Quantity = 1,
                            UnitPrice = 1575.94m
                        },
                        new
                        {
                            ProductId = new Guid("d3a61201-1a3f-44cd-a318-194f0e14c1ae"),
                            Name = "Keyboard",
                            OrderId = new Guid("1adf054d-b6eb-40da-915b-38cba82c5b2c"),
                            Quantity = 2,
                            UnitPrice = 2176.64m
                        },
                        new
                        {
                            ProductId = new Guid("643cf904-fb02-48cb-abf7-e267a4e005e2"),
                            Name = "Printer",
                            OrderId = new Guid("1adf054d-b6eb-40da-915b-38cba82c5b2c"),
                            Quantity = 3,
                            UnitPrice = 3347.77m
                        },
                        new
                        {
                            ProductId = new Guid("a62563ed-5fd6-4642-af9c-7753bab6f2bc"),
                            Name = "Laptop",
                            OrderId = new Guid("704ac39c-4331-491d-a8ec-01375655eeb5"),
                            Quantity = 4,
                            UnitPrice = 4146.37m
                        },
                        new
                        {
                            ProductId = new Guid("989364c1-c9a8-4642-bd4e-a8a4f1e4479a"),
                            Name = "Webcam",
                            OrderId = new Guid("704ac39c-4331-491d-a8ec-01375655eeb5"),
                            Quantity = 2,
                            UnitPrice = 1903.32m
                        },
                        new
                        {
                            ProductId = new Guid("cf197087-f5d2-4fd3-a201-4521082ed8fa"),
                            Name = "Mouse",
                            OrderId = new Guid("704ac39c-4331-491d-a8ec-01375655eeb5"),
                            Quantity = 2,
                            UnitPrice = 2447.75m
                        },
                        new
                        {
                            ProductId = new Guid("dbc6eaa5-12fa-4776-9f92-634dff12b017"),
                            Name = "Laptop",
                            OrderId = new Guid("704ac39c-4331-491d-a8ec-01375655eeb5"),
                            Quantity = 3,
                            UnitPrice = 1985.53m
                        },
                        new
                        {
                            ProductId = new Guid("5f7668d4-37bf-4e8d-b634-4205c0e370d9"),
                            Name = "USB Drive",
                            OrderId = new Guid("65589077-31fa-41e3-a271-2c9af2052046"),
                            Quantity = 4,
                            UnitPrice = 1823.50m
                        },
                        new
                        {
                            ProductId = new Guid("3d5ccc4e-8931-4ff7-8180-9ad98bdf182a"),
                            Name = "Webcam",
                            OrderId = new Guid("65589077-31fa-41e3-a271-2c9af2052046"),
                            Quantity = 2,
                            UnitPrice = 4082.51m
                        },
                        new
                        {
                            ProductId = new Guid("2f656480-ea6a-4f1b-9aa8-cc01e966787d"),
                            Name = "Smartphone",
                            OrderId = new Guid("65589077-31fa-41e3-a271-2c9af2052046"),
                            Quantity = 2,
                            UnitPrice = 4163.20m
                        },
                        new
                        {
                            ProductId = new Guid("2b752a51-0631-4c6d-b0b5-2677e8a2910c"),
                            Name = "Tablet",
                            OrderId = new Guid("65589077-31fa-41e3-a271-2c9af2052046"),
                            Quantity = 3,
                            UnitPrice = 1118.05m
                        },
                        new
                        {
                            ProductId = new Guid("4df7df90-23e5-4685-a886-a91226de4cde"),
                            Name = "Headset",
                            OrderId = new Guid("65589077-31fa-41e3-a271-2c9af2052046"),
                            Quantity = 4,
                            UnitPrice = 4124.81m
                        },
                        new
                        {
                            ProductId = new Guid("896d5323-fce9-4ae4-be73-1396ed39558c"),
                            Name = "Smartphone",
                            OrderId = new Guid("364c23bf-7770-4b90-87cc-4dbe51a72f80"),
                            Quantity = 1,
                            UnitPrice = 2748.92m
                        },
                        new
                        {
                            ProductId = new Guid("a17847cd-fcbf-4e35-9bed-a010bfefe594"),
                            Name = "USB Drive",
                            OrderId = new Guid("364c23bf-7770-4b90-87cc-4dbe51a72f80"),
                            Quantity = 2,
                            UnitPrice = 2996.85m
                        },
                        new
                        {
                            ProductId = new Guid("1c0fe3e5-d953-4911-b007-a12f5000344e"),
                            Name = "Printer",
                            OrderId = new Guid("cb51b1e5-1146-4351-837f-d5a2100ab289"),
                            Quantity = 2,
                            UnitPrice = 4775.67m
                        },
                        new
                        {
                            ProductId = new Guid("e48041eb-78a3-4413-8cf4-18fb3f5cb42e"),
                            Name = "USB Drive",
                            OrderId = new Guid("90085c45-7a4e-49a6-8b9a-9ec70297b4ad"),
                            Quantity = 3,
                            UnitPrice = 4845.13m
                        },
                        new
                        {
                            ProductId = new Guid("65565ab1-33e2-4101-b866-0b7fb34969b5"),
                            Name = "Printer",
                            OrderId = new Guid("90085c45-7a4e-49a6-8b9a-9ec70297b4ad"),
                            Quantity = 3,
                            UnitPrice = 509.27m
                        },
                        new
                        {
                            ProductId = new Guid("be08fb09-00d1-442c-90af-02f565c4615e"),
                            Name = "Headset",
                            OrderId = new Guid("90085c45-7a4e-49a6-8b9a-9ec70297b4ad"),
                            Quantity = 3,
                            UnitPrice = 602.16m
                        },
                        new
                        {
                            ProductId = new Guid("a0a99057-ba0a-4bd4-8740-a66f684b3873"),
                            Name = "Monitor",
                            OrderId = new Guid("90085c45-7a4e-49a6-8b9a-9ec70297b4ad"),
                            Quantity = 4,
                            UnitPrice = 3863.48m
                        },
                        new
                        {
                            ProductId = new Guid("f0811d22-85e7-42ab-818d-00b2a2b2b0b9"),
                            Name = "Laptop",
                            OrderId = new Guid("90085c45-7a4e-49a6-8b9a-9ec70297b4ad"),
                            Quantity = 3,
                            UnitPrice = 4582.78m
                        },
                        new
                        {
                            ProductId = new Guid("19382867-74f7-4f07-b27d-48d4071d9eab"),
                            Name = "Webcam",
                            OrderId = new Guid("8ee3859f-a583-4fd8-8a20-46b5d84a47a0"),
                            Quantity = 4,
                            UnitPrice = 1054.97m
                        },
                        new
                        {
                            ProductId = new Guid("290edf76-e561-4639-a856-21df5ca8f54f"),
                            Name = "Webcam",
                            OrderId = new Guid("8c1b2538-9008-499f-9f16-95b69960eced"),
                            Quantity = 4,
                            UnitPrice = 4939.99m
                        },
                        new
                        {
                            ProductId = new Guid("ca3e0e5f-00d2-472b-b4a6-bb42295783db"),
                            Name = "USB Drive",
                            OrderId = new Guid("8c1b2538-9008-499f-9f16-95b69960eced"),
                            Quantity = 1,
                            UnitPrice = 3585.18m
                        },
                        new
                        {
                            ProductId = new Guid("dadb35ab-5d0c-44b9-b079-6008334db905"),
                            Name = "Laptop",
                            OrderId = new Guid("8c1b2538-9008-499f-9f16-95b69960eced"),
                            Quantity = 1,
                            UnitPrice = 3927.57m
                        },
                        new
                        {
                            ProductId = new Guid("36843148-963f-4a91-89a9-9b0ca17408e4"),
                            Name = "Monitor",
                            OrderId = new Guid("8c1b2538-9008-499f-9f16-95b69960eced"),
                            Quantity = 3,
                            UnitPrice = 700.86m
                        },
                        new
                        {
                            ProductId = new Guid("b2af208c-d8d2-421e-9672-f7a4bc784317"),
                            Name = "Keyboard",
                            OrderId = new Guid("5da8ed8e-b31c-453a-a215-479048514319"),
                            Quantity = 3,
                            UnitPrice = 1463.14m
                        },
                        new
                        {
                            ProductId = new Guid("e0056829-58cf-4d20-ad3e-3f227dc365d3"),
                            Name = "Tablet",
                            OrderId = new Guid("5da8ed8e-b31c-453a-a215-479048514319"),
                            Quantity = 4,
                            UnitPrice = 4341.61m
                        },
                        new
                        {
                            ProductId = new Guid("746fee63-baa6-4c03-b2fe-939e120c4b5d"),
                            Name = "USB Drive",
                            OrderId = new Guid("7f17be03-7c57-4a02-b6ff-5d51a997d25c"),
                            Quantity = 3,
                            UnitPrice = 1316.08m
                        },
                        new
                        {
                            ProductId = new Guid("4bd617e7-daa2-41ef-add2-e69c1d344d67"),
                            Name = "Tablet",
                            OrderId = new Guid("7f17be03-7c57-4a02-b6ff-5d51a997d25c"),
                            Quantity = 4,
                            UnitPrice = 4515.54m
                        },
                        new
                        {
                            ProductId = new Guid("2a55e60d-a352-49c1-aaba-70a34fda379a"),
                            Name = "Monitor",
                            OrderId = new Guid("7f17be03-7c57-4a02-b6ff-5d51a997d25c"),
                            Quantity = 1,
                            UnitPrice = 4234.90m
                        },
                        new
                        {
                            ProductId = new Guid("ea8725c7-ad71-4d42-9799-3ffc1ccc62b4"),
                            Name = "Printer",
                            OrderId = new Guid("02b34547-c1a4-42b4-ab37-1a799d3a5417"),
                            Quantity = 3,
                            UnitPrice = 1827.01m
                        },
                        new
                        {
                            ProductId = new Guid("61afb093-96ec-440c-9eef-0d56c92f2af5"),
                            Name = "Printer",
                            OrderId = new Guid("02b34547-c1a4-42b4-ab37-1a799d3a5417"),
                            Quantity = 4,
                            UnitPrice = 2121.95m
                        },
                        new
                        {
                            ProductId = new Guid("cd52644d-de9e-486a-8bad-046ca6b81f0e"),
                            Name = "USB Drive",
                            OrderId = new Guid("02b34547-c1a4-42b4-ab37-1a799d3a5417"),
                            Quantity = 3,
                            UnitPrice = 2323.76m
                        },
                        new
                        {
                            ProductId = new Guid("6335be91-b7f1-41a2-8460-5ed095f3da27"),
                            Name = "Keyboard",
                            OrderId = new Guid("3c90739f-80f9-4fee-aa41-7fcf1bc27551"),
                            Quantity = 2,
                            UnitPrice = 2603.29m
                        },
                        new
                        {
                            ProductId = new Guid("a607702b-32e6-41aa-8853-2e9319fbf6d7"),
                            Name = "Keyboard",
                            OrderId = new Guid("3c90739f-80f9-4fee-aa41-7fcf1bc27551"),
                            Quantity = 1,
                            UnitPrice = 417.32m
                        },
                        new
                        {
                            ProductId = new Guid("c7cbd6da-d455-449f-8738-35eb468ae87b"),
                            Name = "Tablet",
                            OrderId = new Guid("cd3dfae4-336e-43a1-af13-d215fc01c27c"),
                            Quantity = 2,
                            UnitPrice = 3440.00m
                        },
                        new
                        {
                            ProductId = new Guid("9fbc1b43-fba7-439c-9de3-36b09310d7fb"),
                            Name = "Tablet",
                            OrderId = new Guid("cd3dfae4-336e-43a1-af13-d215fc01c27c"),
                            Quantity = 1,
                            UnitPrice = 1620.53m
                        },
                        new
                        {
                            ProductId = new Guid("872ac3ab-fa4e-4c2f-98df-c0853e8c8e1d"),
                            Name = "Headset",
                            OrderId = new Guid("cd3dfae4-336e-43a1-af13-d215fc01c27c"),
                            Quantity = 2,
                            UnitPrice = 3067.24m
                        },
                        new
                        {
                            ProductId = new Guid("44697429-ed59-4998-8467-48d033d27570"),
                            Name = "Printer",
                            OrderId = new Guid("01916843-8a88-4c4f-8d52-2c3758672a6d"),
                            Quantity = 4,
                            UnitPrice = 1338.49m
                        },
                        new
                        {
                            ProductId = new Guid("b46666b0-a228-4ce7-9529-8bdcc58db6b0"),
                            Name = "Tablet",
                            OrderId = new Guid("01916843-8a88-4c4f-8d52-2c3758672a6d"),
                            Quantity = 1,
                            UnitPrice = 3677.23m
                        },
                        new
                        {
                            ProductId = new Guid("712744b6-5433-44b0-89d6-03a88d6d6c45"),
                            Name = "Mouse",
                            OrderId = new Guid("5d6401b6-1d27-4f30-96d8-aee89ece5604"),
                            Quantity = 3,
                            UnitPrice = 2015.65m
                        },
                        new
                        {
                            ProductId = new Guid("c6ecc2be-cc34-4337-988b-6abfd0d410ca"),
                            Name = "Monitor",
                            OrderId = new Guid("7e4c0803-df8b-4a7d-a58a-f8a104595acb"),
                            Quantity = 1,
                            UnitPrice = 671.56m
                        },
                        new
                        {
                            ProductId = new Guid("6e13d87b-98db-4087-99dc-62f5b71f4660"),
                            Name = "Tablet",
                            OrderId = new Guid("7e4c0803-df8b-4a7d-a58a-f8a104595acb"),
                            Quantity = 4,
                            UnitPrice = 2004.90m
                        },
                        new
                        {
                            ProductId = new Guid("5115a058-a8c4-4363-b2b8-eec499235b49"),
                            Name = "Smartphone",
                            OrderId = new Guid("88d81a15-bc6c-495e-8f3f-218a5b85fac2"),
                            Quantity = 3,
                            UnitPrice = 3564.89m
                        },
                        new
                        {
                            ProductId = new Guid("052c9e30-b187-4547-bf2e-3dbb1bf69f1e"),
                            Name = "Laptop",
                            OrderId = new Guid("88d81a15-bc6c-495e-8f3f-218a5b85fac2"),
                            Quantity = 4,
                            UnitPrice = 2265.47m
                        },
                        new
                        {
                            ProductId = new Guid("32bb8153-9b4b-4017-80d9-6ad421399ec7"),
                            Name = "Printer",
                            OrderId = new Guid("88d81a15-bc6c-495e-8f3f-218a5b85fac2"),
                            Quantity = 4,
                            UnitPrice = 3534.94m
                        },
                        new
                        {
                            ProductId = new Guid("54a91c02-5839-4577-a696-d5fb63266414"),
                            Name = "Monitor",
                            OrderId = new Guid("88d81a15-bc6c-495e-8f3f-218a5b85fac2"),
                            Quantity = 3,
                            UnitPrice = 4856.31m
                        },
                        new
                        {
                            ProductId = new Guid("c493bd64-f37d-4799-b963-3722d319fae6"),
                            Name = "Smartphone",
                            OrderId = new Guid("e115edaa-ea9f-4bff-babd-671ceeafe26c"),
                            Quantity = 4,
                            UnitPrice = 1833.05m
                        },
                        new
                        {
                            ProductId = new Guid("87d75e54-6e8c-48a6-a72f-f163790cf3b7"),
                            Name = "USB Drive",
                            OrderId = new Guid("e115edaa-ea9f-4bff-babd-671ceeafe26c"),
                            Quantity = 3,
                            UnitPrice = 4504.88m
                        },
                        new
                        {
                            ProductId = new Guid("5dc73627-0008-41d1-9559-054f223cd02d"),
                            Name = "Monitor",
                            OrderId = new Guid("671212b2-8732-441e-81c9-7bfa1bbca4e6"),
                            Quantity = 4,
                            UnitPrice = 288.43m
                        },
                        new
                        {
                            ProductId = new Guid("da334d29-99fa-4745-abd7-e26bb380fbc4"),
                            Name = "Headset",
                            OrderId = new Guid("671212b2-8732-441e-81c9-7bfa1bbca4e6"),
                            Quantity = 3,
                            UnitPrice = 4817.88m
                        },
                        new
                        {
                            ProductId = new Guid("ca6ecd2b-c0c1-48e3-b35b-2a31f839daa1"),
                            Name = "Webcam",
                            OrderId = new Guid("671212b2-8732-441e-81c9-7bfa1bbca4e6"),
                            Quantity = 3,
                            UnitPrice = 2971.17m
                        },
                        new
                        {
                            ProductId = new Guid("4ea6c1d5-95bc-410b-90de-68e5a4ed894e"),
                            Name = "Laptop",
                            OrderId = new Guid("671212b2-8732-441e-81c9-7bfa1bbca4e6"),
                            Quantity = 3,
                            UnitPrice = 3832.80m
                        },
                        new
                        {
                            ProductId = new Guid("dfe39338-1ba5-4c0d-906a-7625646e7b16"),
                            Name = "Keyboard",
                            OrderId = new Guid("8d04a8e4-5c06-4d30-b011-b7fe9af5bc21"),
                            Quantity = 4,
                            UnitPrice = 4731.80m
                        },
                        new
                        {
                            ProductId = new Guid("9b6fbbdd-a8d9-4ce2-9afb-9223396c61dc"),
                            Name = "Printer",
                            OrderId = new Guid("8d04a8e4-5c06-4d30-b011-b7fe9af5bc21"),
                            Quantity = 4,
                            UnitPrice = 4399.73m
                        },
                        new
                        {
                            ProductId = new Guid("d5b76a06-ff65-4c27-a5c3-d43efcc05b7b"),
                            Name = "Smartphone",
                            OrderId = new Guid("8d04a8e4-5c06-4d30-b011-b7fe9af5bc21"),
                            Quantity = 2,
                            UnitPrice = 575.75m
                        },
                        new
                        {
                            ProductId = new Guid("ce338974-f388-457c-a331-994e604937f7"),
                            Name = "Laptop",
                            OrderId = new Guid("595f3d82-1954-4398-83f5-38bb445abe6c"),
                            Quantity = 3,
                            UnitPrice = 2481.85m
                        },
                        new
                        {
                            ProductId = new Guid("9625b626-9a4d-4a57-acf1-0ed6e6f6654d"),
                            Name = "Smartphone",
                            OrderId = new Guid("595f3d82-1954-4398-83f5-38bb445abe6c"),
                            Quantity = 4,
                            UnitPrice = 1878.88m
                        },
                        new
                        {
                            ProductId = new Guid("c33a9509-f224-46d9-af99-4137c17fdc98"),
                            Name = "USB Drive",
                            OrderId = new Guid("595f3d82-1954-4398-83f5-38bb445abe6c"),
                            Quantity = 4,
                            UnitPrice = 2049.93m
                        },
                        new
                        {
                            ProductId = new Guid("1b217691-db97-4ae7-afd8-b85ee51428ce"),
                            Name = "Smartphone",
                            OrderId = new Guid("2cbde594-d503-4b9e-a200-2bdf5c2416f6"),
                            Quantity = 3,
                            UnitPrice = 3941.80m
                        },
                        new
                        {
                            ProductId = new Guid("d88bcabd-d4e3-4ebc-a983-ac030dc73028"),
                            Name = "Keyboard",
                            OrderId = new Guid("2cbde594-d503-4b9e-a200-2bdf5c2416f6"),
                            Quantity = 4,
                            UnitPrice = 2460.07m
                        },
                        new
                        {
                            ProductId = new Guid("b9531b5c-9589-4b0f-b455-36a7af640b4e"),
                            Name = "Laptop",
                            OrderId = new Guid("2cbde594-d503-4b9e-a200-2bdf5c2416f6"),
                            Quantity = 4,
                            UnitPrice = 2699.20m
                        },
                        new
                        {
                            ProductId = new Guid("bd6cb0ed-552a-4c5e-953b-43c9236d1a0e"),
                            Name = "Laptop",
                            OrderId = new Guid("2cbde594-d503-4b9e-a200-2bdf5c2416f6"),
                            Quantity = 2,
                            UnitPrice = 1517.84m
                        },
                        new
                        {
                            ProductId = new Guid("e106147a-9b3b-4f37-b883-6a9459c9c4ab"),
                            Name = "Printer",
                            OrderId = new Guid("2cbde594-d503-4b9e-a200-2bdf5c2416f6"),
                            Quantity = 2,
                            UnitPrice = 401.15m
                        });
                });

            modelBuilder.Entity("OrderViewer.Service.OrderAPI.Models.Product", b =>
                {
                    b.HasOne("OrderViewer.Service.OrderAPI.Models.Order", "Order")
                        .WithMany("Products")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OrderViewer.Service.OrderAPI.Models.Order", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
